__BASE__: "Base.yaml"

TASK_NAME: 'aloha_pourblueplate'

POLICY:
  POLICY_NAME: "ACT"
  BACKBONE: "resnet18"
  CHUNK_SIZE: 5
  STATE_DIM: 14
  ENC_LAYERS: 4
  DEC_LAYERS: 1
  USE_UNCERTAINTY: False
  UNCERTAINTY_RANGE: [-10, 10]
  USE_CLIP: False
  CLIP_PATH: "./pretrained/CLIP_ckpts"
  KL_WEIGHT: 50

TRAIN:
  NUM_ITERATIONS: 10000
  LOG_INTERVAL: 100
  SAVE_CHECKPOINT_INTERVAL: 1000
  BATCH_SIZE: 16
  LR: 0.00001
  LR_BACKBONE: 0.00001
  DECAY_LR_ITER_STEPS: []
  DATA_SAMPLE_MODE: 'random'

EVAL:
  DATA_EVAL_RATIO: 0.0
  INFERENCE_MAX_STEPS: 2000
  VALID_CHUNK: 5
  LIMIT_MAX_MOVE: True

DATA:
  CAMERA_NAMES: ['cam_high', 'cam_left_wrist', 'cam_right_wrist']
  IMG_RESIZE_SHAPE: [320, 240]
  ROI_RESIZE_SHAPE: [320, 240]
  INPUT_KEYS: ['task_instruction', 'observations/qpos_obs',]
  NORM_KEYS: ['action', 'observations/qpos_obs',]
  PAST_OBSERVATION_LEN: 1
  OBSERVATION_SAMPLE_INTERVAL: 1
  PAST_ACTION_LEN: 0
  PAST_ACTION_SAMPLE_INTERVAL: 1
  ACTION_SAMPLE_INTERVAL: 4