__BASE__: "Base.yaml"

TASK_NAME: 'aloha_beverage'

POLICY:
  POLICY_NAME: "AlohaGripper_ACT"
  BACKBONE: "dinov2_s"
  BACKBONE_PATH: "./pretrained/dinov2_vits14_pretrain.pth"
  CHUNK_SIZE: 20
  STATE_DIM: 14
  ENC_LAYERS: 0
  DEC_LAYERS: 3
  OUTPUT_MODE: 'absolute'
  USE_UNCERTAINTY: True
  UNCERTAINTY_RANGE: [-10, 10]
  USE_CLIP: False
  CLIP_PATH: "./pretrained/CLIP_ckpts"
  EXTERNAL_DET: "YOLOv10_beverage"
  EXTERNAL_DET_SCALE_FACTOR: 1.3
  YOLO_PATH: "./pretrained/yolov10_aloha_beverage.pt"
  STATUS_NUM: 10
  STATUS_PREDICT: True
  GRID_MASK: True

TRAIN:
  NUM_ITERATIONS: 15000
  LOG_INTERVAL: 100
  SAVE_CHECKPOINT_INTERVAL: 1000
  BATCH_SIZE: 18
  LR: 0.00001
  LR_BACKBONE: 0.000001
  DECAY_LR_ITER_STEPS: []
  DATA_SAMPLE_MODE: 'random'

EVAL:
  DATA_EVAL_RATIO: 0.0
  INFERENCE_MAX_STEPS: 2000
  VALID_CHUNK: 5
  CHUNK_SMOOTH: -1

DATA:
  CAMERA_NAMES: ['cam_high', 'cam_left_wrist', 'cam_right_wrist']
  IMG_RESIZE_SHAPE: [322, 238]
  ROI_RESIZE_SHAPE: [322, 238]
  INPUT_KEYS: ['observations/effort_obs', 'observations/qpos_obs', 'observations/qvel_obs', 'past_action']
  NORM_KEYS: ['action', 'observations/effort_obs', 'observations/qpos_obs', 'observations/qvel_obs']
  PAST_OBSERVATION_LEN: 20
  OBSERVATION_SAMPLE_INTERVAL: 10
  PAST_ACTION_LEN: 5
  PAST_ACTION_SAMPLE_INTERVAL: 1
  ACTION_SAMPLE_INTERVAL: 8