__BASE__: "Base.yaml"

TASK_NAME: 'isaac_singlecolorbox'

POLICY:
  POLICY_NAME: "Diffusion"
  BACKBONE: "resnet18"
  CHUNK_SIZE: 20
  STATE_DIM: 9
  USE_CLIP: True
  CLIP_PATH: "./pretrained/CLIP_ckpts"

TRAIN:
  NUM_ITERATIONS: 8000
  LOG_INTERVAL: 100
  SAVE_CHECKPOINT_INTERVAL: 1000
  BATCH_SIZE: 32
  LR: 0.00001
  LR_BACKBONE: 0.00001
  DECAY_LR_ITER_STEPS: []
  DATA_SAMPLE_MODE: 'random'

EVAL:
  DATA_EVAL_RATIO: 0.0
  INFERENCE_MAX_STEPS: 1000
  TEST_ENVI_NUM: 100
  TEST_ENVI_BATCH_NUM: 5
  CTRL_STEP_INTERVAL: 2

DATA:
  CAMERA_NAMES: ['exterior_camera1', 'exterior_camera2', 'wrist_camera']
  IMG_RESIZE_SHAPE: [320, 240]
  INPUT_KEYS: ['task_instruction', 'observations/end_observation']
  NORM_KEYS: ['action', 'observations/end_observation',]
  PAST_OBSERVATION_LEN: 1
  OBSERVATION_SAMPLE_INTERVAL: 1
  PAST_ACTION_LEN: 0
  PAST_ACTION_SAMPLE_INTERVAL: 1
  FRANKA_XYZ_RANGE: [0.2, 0.8, -0.5, 0.5, 0.4, 0.8] # [x_min, x_max, y_min, y_max, z_min, z_max]