__BASE__: "Base.yaml"

TASK_NAME: 'droid_pretrain'
SEED: 1

POLICY:
  POLICY_NAME: "DroidPretrain_ACT"
  BACKBONE: "dinov2_s"
  CHUNK_SIZE: 10
  STATE_DIM: 7
  ENC_LAYERS: 0
  DEC_LAYERS: 3
  OUTPUT_MODE: 'relative'
  USE_UNCERTAINTY: True
  UNCERTAINTY_RANGE: [-10, 10]
  USE_CLIP: False
  CLIP_PATH: "/home/cvte/twilight/home/data/ckpts/CLIP_ckpts"
  GRID_MASK: True

TRAIN:
  NUM_ITERATIONS: 100000
  LOG_INTERVAL: 100
  SAVE_CHECKPOINT_INTERVAL: 1000
  BATCH_SIZE: 12
  LR: 0.00001
  LR_BACKBONE: 0.0000001
  DECAY_LR_ITER_STEPS: []
  DATA_SAMPLE_MODE: 'random'
  FEATURE_REGULARIZATION: True

EVAL:
  DATA_EVAL_RATIO: 0.0
  INFERENCE_MAX_STEPS: 2500
  TEST_ENVI_NUM: 100
  TEST_ENVI_BATCH_NUM: 5
  CTRL_STEP_INTERVAL: 2

DATA:
  CAMERA_NAMES: ['exterior_image_1_left', 'exterior_image_2_left', 'wrist_image_left']
  IMG_RESIZE_SHAPE: [518, 518]
  ROI_RESIZE_SHAPE: [518, 518]
  INPUT_KEYS: ['task_instruction', 'observation/cartesian_position', 'observation/gripper_position', 'observation/joint_position', 'past_action']
  NORM_KEYS: ['action', 'observation/cartesian_position', 'observation/gripper_position', 'observation/joint_position']
  PAST_OBSERVATION_LEN: 5
  OBSERVATION_SAMPLE_INTERVAL: 10
  PAST_ACTION_LEN: 5
  PAST_ACTION_SAMPLE_INTERVAL: 1
  LOAD_INDICE_PATH: "datasets/droid/droid_pretrain_indice.pkl"
  PRETRAIN_VISION_INSTRUCTION: "future_frame" # "future_frame" or "grasp_keyframe"