__BASE__: "Base.yaml"

TASK_NAME: 'isaac_multicolorbox'
ONSCREEN_RENDER: True

POLICY:
  POLICY_NAME: "IsaacGripper_ACT"
  BACKBONE: "dinov2_s"
  BACKBONE_PATH: "./pretrained/dinov2_vits14_pretrain.pth"
  CHUNK_SIZE: 10
  STATE_DIM: 9
  ENC_LAYERS: 0
  DEC_LAYERS: 3
  USE_UNCERTAINTY: True
  UNCERTAINTY_RANGE: [-10, 10]
  USE_CLIP: False
  CLIP_PATH: "./pretrained/CLIP_ckpts"
  EXTERNAL_DET: "LanguageMultiColorFilter"
  EXTERNAL_DET_SCALE_FACTOR: 4.0
  STATUS_NUM: 3
  STATUS_PREDICT: True
  GRID_MASK: False

TRAIN:
  NUM_ITERATIONS: 12000
  LOG_INTERVAL: 100
  SAVE_CHECKPOINT_INTERVAL: 1000
  BATCH_SIZE: 64
  LR: 0.00001
  LR_BACKBONE: 0.000001
  DECAY_LR_ITER_STEPS: []
  DATA_SAMPLE_MODE: 'random'

EVAL:
  DATA_EVAL_RATIO: 0.0
  INFERENCE_MAX_STEPS: 2500
  TEST_ENVI_NUM: 100
  TEST_ENVI_BATCH_NUM: 5
  CTRL_STEP_INTERVAL: 2

DATA:
  CAMERA_NAMES: ['exterior_camera1', 'exterior_camera2', 'wrist_camera']
  IMG_RESIZE_SHAPE: [154, 112]
  ROI_RESIZE_SHAPE: [154, 112]
  INPUT_KEYS: ['task_instruction', 'observations/end_observation', 'observations/joint_observation', 'past_action']
  NORM_KEYS: ['action', 'observations/end_observation', 'observations/joint_observation']
  PAST_OBSERVATION_LEN: 5
  OBSERVATION_SAMPLE_INTERVAL: 10
  PAST_ACTION_LEN: 5
  PAST_ACTION_SAMPLE_INTERVAL: 1
  FRANKA_XYZ_RANGE: [0.2, 0.8, -0.5, 0.5, 0.4, 0.8] # [x_min, x_max, y_min, y_max, z_min, z_max]