__BASE__: "Base.yaml"

TASK_NAME: 'aloha_singleobjgrasp'
ONSCREEN_RENDER: True

POLICY:
  POLICY_NAME: "AlohaGripper_ACT"
  BACKBONE: "dinov2_s"
  BACKBONE_PATH: "./pretrained/dinov2_vits14_pretrain.pth"
  CHUNK_SIZE: 10
  STATE_DIM: 14
  ENC_LAYERS: 0
  DEC_LAYERS: 3
  USE_UNCERTAINTY: True
  UNCERTAINTY_RANGE: [-10, 10]
  USE_CLIP: False
  CLIP_PATH: "./pretrained/CLIP_ckpts"
  EXTERNAL_DET: "YOLOv10_airphonebox"
  EXTERNAL_DET_SCALE_FACTOR: 2.0
  YOLO_PATH: "./pretrained/yolov10_airphonebox.pt"
  STATUS_NUM: 1
  STATUS_PREDICT: True

TRAIN:
  NUM_ITERATIONS: 12000
  LOG_INTERVAL: 100
  SAVE_CHECKPOINT_INTERVAL: 1000
  BATCH_SIZE: 14
  LR: 0.00001
  LR_BACKBONE: 0.00001
  DECAY_LR_ITER_STEPS: []
  DATA_SAMPLE_MODE: 'random'

EVAL:
  DATA_EVAL_RATIO: 0.0
  INFERENCE_MAX_STEPS: 400
  TEST_ENVI_NUM: 100
  TEST_ENVI_BATCH_NUM: 5
  CTRL_STEP_INTERVAL: 2

DATA:
  CAMERA_NAMES: ['cam_high', 'cam_left_wrist', 'cam_right_wrist']
  IMG_RESIZE_SHAPE: [322, 238]
  ROI_RESIZE_SHAPE: [322, 238]
  INPUT_KEYS: ['observations/effort', 'observations/qpos', 'observations/qvel', 'past_action']
  NORM_KEYS: ['action', 'observations/effort', 'observations/qpos', 'observations/qvel']
  PAST_OBSERVATION_LEN: 5
  OBSERVATION_SAMPLE_INTERVAL: 10
  PAST_ACTION_LEN: 5
  PAST_ACTION_SAMPLE_INTERVAL: 1