__BASE__: "Base.yaml"

TASK_NAME: 'isaac_gripper'

POLICY:
  POLICY_NAME: "IsaacGripper_ACT"
  CHUNK_SIZE: 40
  STATE_DIM: 7
  ENC_LAYERS: 1
  DEC_LAYERS: 6
  USE_VAE: False

TRAIN:
  NUM_ITERATIONS: 500000
  BATCH_SIZE: 32

EVAL:
  DATA_EVAL_RATIO: 0.01

DATA:
  CAMERA_NAMES: ['exterior_camera1', 'exterior_camera2', 'top_camera', 'wrist_camera']
  INPUT_KEYS: ['action', 'observations/end_observation', 'observations/joint_observation',]
  NORM_KEYS: ['action', 'observations/end_observation', 'observations/joint_observation']
  PAST_OBSERVATION_LEN: 20
  PAST_ACTION_LEN: 50